#!/usr/bin/env node
/**
 * Generates the typed message catalogs (src/lib/i18n/messages/{en,nl,de,fr,tr}.ts)
 * from the JSON source of truth in src/lib/i18n/catalog/*.json.
 *
 * Each catalog file maps a key to its four translations:
 *   { "namespace.key": { "en": "...", "nl": "...", "de": "...", "fr": "...", "tr": "..." } }
 *
 * English is canonical: en.ts exports `MessageKey = keyof typeof en`, so a key
 * missing from any language is a compile error. Run: `node scripts/gen-i18n.mjs`.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CATALOG_DIR = join(ROOT, 'src/lib/i18n/catalog');
const OUT_DIR = join(ROOT, 'src/lib/i18n/messages');
const LOCALES = ['en', 'nl', 'de', 'fr', 'tr'];

const merged = {}; // key -> { en, nl, de, fr }
const origin = {}; // key -> file (for conflict reporting)

for (const file of readdirSync(CATALOG_DIR).filter((f) => f.endsWith('.json')).sort()) {
  const entries = JSON.parse(readFileSync(join(CATALOG_DIR, file), 'utf8'));
  for (const [key, langs] of Object.entries(entries)) {
    if (key in merged) {
      const prev = JSON.stringify(merged[key]);
      const next = JSON.stringify(langs);
      if (prev !== next) {
        throw new Error(
          `Conflicting translations for "${key}" in ${file} vs ${origin[key]}.`
        );
      }
      continue;
    }
    for (const l of LOCALES) {
      if (typeof langs[l] !== 'string') {
        throw new Error(`Key "${key}" in ${file} is missing "${l}".`);
      }
    }
    merged[key] = langs;
    origin[key] = file;
  }
}

const keys = Object.keys(merged).sort();
const esc = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

function body(locale) {
  return keys.map((k) => `  '${esc(k)}': '${esc(merged[k][locale])}',`).join('\n');
}

const enHeader = `/**
 * English message catalog — the canonical key set. GENERATED by
 * scripts/gen-i18n.mjs from src/lib/i18n/catalog/*.json. Do not edit by hand;
 * edit the catalog JSON and re-run \`node scripts/gen-i18n.mjs\`.
 *
 * Every other language is typed \`Record<MessageKey, string>\`, so a missing
 * translation is a compile error. Use \`{name}\` for interpolated values.
 */
export const en = {
${body('en')}
} as const;

export type MessageKey = keyof typeof en;
`;
writeFileSync(join(OUT_DIR, 'en.ts'), enHeader);

for (const locale of LOCALES.filter((l) => l !== 'en')) {
  const label = { nl: 'Dutch', de: 'German', fr: 'French' }[locale];
  const out = `import type { MessageKey } from '@/lib/i18n/messages/en';

/** ${label} message catalog. GENERATED by scripts/gen-i18n.mjs — do not edit. */
export const ${locale}: Record<MessageKey, string> = {
${body(locale)}
};
`;
  writeFileSync(join(OUT_DIR, `${locale}.ts`), out);
}

console.log(`Generated ${keys.length} keys × ${LOCALES.length} locales.`);
